In [2]:
cd TFM_UNIR

C:\Users\Jhon_\TFM_UNIR

In [3]:
import pandas as pd

In [5]:
# Ajustar la ruta del archivo
file_path = './TFM_UNIR/data/raw/BINANCE_BTCUSD.P, 60min.csv'
df = pd.read_csv(file_path)

In [7]:
# Mostrar las primeras filas del DataFrame
print(df.head())

                        time     open     high      low    close  Bullish  \
0  2022-04-20T02:00:00-05:00  41460.2  41633.7  41286.9  41334.2      NaN
1  2022-04-20T03:00:00-05:00  41334.2  41516.9  41303.3  41477.5      NaN
2  2022-04-20T04:00:00-05:00  41477.4  41721.1  41453.0  41537.7      NaN
3  2022-04-20T05:00:00-05:00  41537.6  41896.0  41447.7  41810.8      NaN
4  2022-04-20T06:00:00-05:00  41810.8  42188.0  41711.4  42089.0      NaN

   Bullish+  Bearish  Bearish+  Bullish Exit  ...  Smart Trail Extremity.1  \
0       NaN      NaN       NaN           NaN  ...                      NaN
1       NaN      NaN       NaN           NaN  ...                      NaN
2       NaN      NaN       NaN           NaN  ...                      NaN
3       NaN      NaN       NaN           NaN  ...                      NaN
4       NaN      NaN       NaN           NaN  ...                      NaN

   RZ R3 Band.1  RZ R2 Band.1  RZ R1 Band.1  RZ S1 Band.1  RZ S2 Band.1  \
0           NaN           NaN           NaN           NaN           NaN
1           NaN           NaN           NaN           NaN           NaN
2           NaN           NaN           NaN           NaN           NaN
3           NaN           NaN           NaN           NaN           NaN
4           NaN           NaN           NaN           NaN           NaN

   RZ S3 Band.1  Neo Lead.1  Neo Lag.1  Custom Alert Condition Highlighter.1
0           NaN         NaN        NaN                                   NaN
1           NaN         NaN        NaN                                   NaN
2           NaN         NaN        NaN                                   NaN
3           NaN         NaN        NaN                                   NaN
4           NaN         NaN        NaN                                   NaN

[5 rows x 51 columns]

In [9]:
#Explorar los datos
# Mostrar las primeras filas del DataFrame
df.head()

# Mostrar información general sobre el DataFrame
df.info()

# Describir las estadísticas básicas de las columnas numéricas
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17827 entries, 0 to 17826
Data columns (total 51 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   time                                  17827 non-null  object
 1   open                                  17827 non-null  float64
 2   high                                  17827 non-null  float64
 3   low                                   17827 non-null  float64
 4   close                                 17827 non-null  float64
 5   Bullish                               0 non-null      float64
 6   Bullish+                              0 non-null      float64
 7   Bearish                               0 non-null      float64
 8   Bearish+                              0 non-null      float64
 9   Bullish Exit                          34 non-null     float64
 10  Bearish Exit                          24 non-null     float64
 11  Trend Strength                        17827 non-null  float64
 12  Take Profit 1                         0 non-null      float64
 13  Stop Loss 1                           0 non-null      float64
 14  Bar Color Value                       17827 non-null  int64
 15  Trend Tracer                          0 non-null      float64
 16  Trend Catcher                         0 non-null      float64
 17  Smart Trail                           17827 non-null  float64
 18  Smart Trail Extremity                 17827 non-null  float64
 19  RZ R3 Band                            0 non-null      float64
 20  RZ R2 Band                            0 non-null      float64
 21  RZ R1 Band                            0 non-null      float64
 22  RZ S1 Band                            0 non-null      float64
 23  RZ S2 Band                            0 non-null      float64
 24  RZ S3 Band                            0 non-null      float64
 25  Neo Lead                              17827 non-null  float64
 26  Neo Lag                               17827 non-null  float64
 27  Custom Alert Condition Highlighter    0 non-null      float64
 28  Bullish.1                             17827 non-null  int64
 29  Bullish+.1                            17827 non-null  int64
 30  Bearish.1                             17827 non-null  int64
 31  Bearish+.1                            17827 non-null  int64
 32  Bullish Exit.1                        34 non-null     float64
 33  Bearish Exit.1                        24 non-null     float64
 34  Trend Strength.1                      17827 non-null  float64
 35  Take Profit 1.1                       0 non-null      float64
 36  Stop Loss 1.1                         0 non-null      float64
 37  Bar Color Value.1                     17827 non-null  int64
 38  Trend Tracer.1                        0 non-null      float64
 39  Trend Catcher.1                       0 non-null      float64
 40  Smart Trail.1                         0 non-null      float64
 41  Smart Trail Extremity.1               0 non-null      float64
 42  RZ R3 Band.1                          0 non-null      float64
 43  RZ R2 Band.1                          0 non-null      float64
 44  RZ R1 Band.1                          0 non-null      float64
 45  RZ S1 Band.1                          0 non-null      float64
 46  RZ S2 Band.1                          0 non-null      float64
 47  RZ S3 Band.1                          0 non-null      float64
 48  Neo Lead.1                            0 non-null      float64
 49  Neo Lag.1                             0 non-null      float64
 50  Custom Alert Condition Highlighter.1  0 non-null      float64
dtypes: float64(44), int64(6), object(1)
memory usage: 6.9+ MB

,open,high,low,close,Bullish,Bullish+,Bearish,Bearish+,Bullish Exit,Bearish Exit,...,Smart Trail Extremity.1,RZ R3 Band.1,RZ R2 Band.1,RZ R1 Band.1,RZ S1 Band.1,RZ S2 Band.1,RZ S3 Band.1,Neo Lead.1,Neo Lag.1,Custom Alert Condition Highlighter.1
count,17827.000000,17827.000000,17827.000000,17827.000000,0.0,0.0,0.0,0.0,34.000000,24.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,31208.402266,31323.861211,31087.866063,31209.272261,NaN,NaN,NaN,NaN,34088.632353,29119.350000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,13572.359597,13635.886739,13501.805997,13573.525559,NaN,NaN,NaN,NaN,15200.356003,14404.897955,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,15621.200000,15740.700000,15440.000000,15622.100000,NaN,NaN,NaN,NaN,17156.300000,15465.700000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,21514.600000,21618.950000,21410.850000,21514.650000,NaN,NaN,NaN,NaN,23323.450000,20086.175000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,27407.500000,27498.600000,27317.200000,27407.500000,NaN,NaN,NaN,NaN,28350.600000,25760.050000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,36542.100000,36654.350000,36445.050000,36542.050000,NaN,NaN,NaN,NaN,43376.975000,28654.050000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,73712.400000,73915.300000,73312.000000,73712.400000,NaN,NaN,NaN,NaN,70747.700000,65164.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# Eliminar columnas con cualquier valor nulo
df_cleaned = df.dropna(axis=1, how='any')

# Mostrar las primeras filas del DataFrame después de la limpieza
print("\nPrimeras filas del DataFrame después de la limpieza:")
print(df_cleaned.head())

# Mostrar información general sobre el DataFrame después de la limpieza
print("\nInformación general del DataFrame después de la limpieza:")
df_cleaned.info()

Primeras filas del DataFrame después de la limpieza:
                        time     open     high      low    close  \
0  2022-04-20T02:00:00-05:00  41460.2  41633.7  41286.9  41334.2
1  2022-04-20T03:00:00-05:00  41334.2  41516.9  41303.3  41477.5
2  2022-04-20T04:00:00-05:00  41477.4  41721.1  41453.0  41537.7
3  2022-04-20T05:00:00-05:00  41537.6  41896.0  41447.7  41810.8
4  2022-04-20T06:00:00-05:00  41810.8  42188.0  41711.4  42089.0

   Trend Strength  Bar Color Value   Smart Trail  Smart Trail Extremity  \
0       46.268069                1  40037.458119           40403.302277
1       49.138325                1  40060.914680           40420.799673
2       52.206034                1  40107.925227           40465.368920
3       55.611135                1  40160.931064           40573.398298
4       59.436435                1  40245.778426           40706.583819

       Neo Lead       Neo Lag  Bullish.1  Bullish+.1  Bearish.1  Bearish+.1  \
0  40806.954280  40298.773963          0           0          0           0
1  40806.954280  40298.773963          0           0          0           0
2  40806.954280  40298.773963          0           0          0           0
3  41076.553692  40342.307384          0           0          0           0
4  41352.467424  40615.934847          0           0          0           0

   Trend Strength.1  Bar Color Value.1
0         46.268069                  1
1         49.138325                  1
2         52.206034                  1
3         55.611135                  1
4         59.436435                  1

Información general del DataFrame después de la limpieza:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17827 entries, 0 to 17826
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   time                   17827 non-null  object
 1   open                   17827 non-null  float64
 2   high                   17827 non-null  float64
 3   low                    17827 non-null  float64
 4   close                  17827 non-null  float64
 5   Trend Strength         17827 non-null  float64
 6   Bar Color Value        17827 non-null  int64
 7   Smart Trail            17827 non-null  float64
 8   Smart Trail Extremity  17827 non-null  float64
 9   Neo Lead               17827 non-null  float64
 10  Neo Lag                17827 non-null  float64
 11  Bullish.1              17827 non-null  int64
 12  Bullish+.1             17827 non-null  int64
 13  Bearish.1              17827 non-null  int64
 14  Bearish+.1             17827 non-null  int64
 15  Trend Strength.1       17827 non-null  float64
 16  Bar Color Value.1      17827 non-null  int64
dtypes: float64(10), int64(6), object(1)
memory usage: 2.3+ MB

In [13]:
# Seleccionar solo las columnas especificadas
columns_to_keep = ['time', 'open', 'high', 'low', 'close', 'Bullish.1', 'Bullish+.1', 'Bearish.1', 'Bearish+.1']
df_cleaned = df[columns_to_keep]

# Mostrar las primeras filas del DataFrame filtrado
print(df_cleaned.head())

# Mostrar información general sobre el DataFrame filtrado
df_cleaned.info()

                        time     open     high      low    close  Bullish.1  \
0  2022-04-20T02:00:00-05:00  41460.2  41633.7  41286.9  41334.2          0
1  2022-04-20T03:00:00-05:00  41334.2  41516.9  41303.3  41477.5          0
2  2022-04-20T04:00:00-05:00  41477.4  41721.1  41453.0  41537.7          0
3  2022-04-20T05:00:00-05:00  41537.6  41896.0  41447.7  41810.8          0
4  2022-04-20T06:00:00-05:00  41810.8  42188.0  41711.4  42089.0          0

   Bullish+.1  Bearish.1  Bearish+.1
0           0          0           0
1           0          0           0
2           0          0           0
3           0          0           0
4           0          0           0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17827 entries, 0 to 17826
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   time        17827 non-null  object
 1   open        17827 non-null  float64
 2   high        17827 non-null  float64
 3   low         17827 non-null  float64
 4   close       17827 non-null  float64
 5   Bullish.1   17827 non-null  int64
 6   Bullish+.1  17827 non-null  int64
 7   Bearish.1   17827 non-null  int64
 8   Bearish+.1  17827 non-null  int64
dtypes: float64(4), int64(4), object(1)
memory usage: 1.2+ MB

In [17]:
# Guardar los datos procesados
df_cleaned.to_csv('./TFM_UNIR/data/processed/BINANCE_BTCUSD_cleaned.csv', index=False)